
[font]
size = 14.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Retina"

[window]
decorations = "none"
dynamic_padding = true

[window.padding]
x = 5
y = 5

[general]
import =["~/Projects/dotfiles/alacritty-themes/github_dark_tritanopia.toml"]
