import =["~/Clones/dotfiles/alacritty-themes/aura.toml"]

[font]
size = 14.0

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Retina"

[window]
decorations = "none"
dynamic_padding = true

[window.padding]
x = 5
y = 5
